apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox
spec:
  replicas: 2
  selector:
    app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
