apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: app-demo
        tier: frontend
    spec:
      volumes:
      - name: datavol
        hostPath:
          path: "/tmp/test"
      containers:
      - name: tomcat-demo
        image: tomcat
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /mydata-data
          name: datavol

